<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\TestProject.props" />
  <PropertyGroup>
    <AssemblyName>DesktopAutomation.IntegrationTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\TestInfrastructure\TestDoubles\*.cs" Link="TestDoubles\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
