name: Build YOLO ONNX
run-name: "Build YOLO ONNX – ${{ inputs.model_key || 'manual' }}"

on:
  workflow_dispatch:
    inputs:
      model_url:
        description: "PT Download-URL (z.B. https://.../yolov8n.pt)"
        required: true
      model_key:
        description: "Kurzname fürs Manifest (z.B. yolov8n)"
        required: true
      imgsz:
        description: "Inputgröße (default 640)"
        default: "640"
      opset:
        description: "ONNX Opset (default 12)"
        default: "12"
      display_name:
        description: "Anzeigename (z.B. YOLOv8 Nano)"
        default: ""
      description:
        description: "Kurzbeschreibung fürs UI"
        default: ""
      ultralytics_spec:
        description: "Ultralytics Version/Fork (pip specifier)"
        default: "ultralytics>=8.0.0"
      torch_spec:
        description: "Torch Version (optional)"
        default: ""
      extra_pip:
        description: "Weitere Pakete (optional)"
        default: ""
      pickle_alias_from:
        description: "OPTIONAL: unbekannte Pickle-Klasse (z.B. HumanModel)"
        default: ""
      pickle_alias_to:
        description: "OPTIONAL: Zielklasse (z.B. DetectionModel)"
        default: "DetectionModel"


jobs:
  export-onnx:
    name: "Export ${{ inputs.model_key }} to ONNX"
    runs-on: ubuntu-latest

    permissions:
      contents: write   # für Release & Commit
      pull-requests: write
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (CPU-only)
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -n "${{ github.event.inputs.torch_spec }}" ]; then
            pip install "${{ github.event.inputs.torch_spec }}"
          fi
          pip install "${{ github.event.inputs.ultralytics_spec }}" onnx onnxsim
          if [ -n "${{ github.event.inputs.extra_pip }}" ]; then
            pip install ${{ github.event.inputs.extra_pip }}
          fi

      - name: Download .pt
        run: |
          set -euo pipefail
          curl -fL "${{ github.event.inputs.model_url }}" -o model.pt
          ls -lah

      - name: Export to ONNX (Ultralytics)
        env:
          IMGSZ: ${{ github.event.inputs.imgsz }}
          OPSET: ${{ github.event.inputs.opset }}
          PICKLE_ALIAS_FROM: ${{ github.event.inputs.pickle_alias_from }}
          PICKLE_ALIAS_TO: ${{ github.event.inputs.pickle_alias_to }}
        run: |
          python - <<'PY'
          import os
          from ultralytics import YOLO
      
          alias_from = os.environ.get("PICKLE_ALIAS_FROM","").strip()
          alias_to   = os.environ.get("PICKLE_ALIAS_TO","DetectionModel").strip()
          if alias_from:
              import ultralytics.nn.tasks as tasks
              setattr(tasks, alias_from, getattr(tasks, alias_to))
      
          imgsz = int(os.environ.get("IMGSZ","640"))
          opset = int(os.environ.get("OPSET","12"))
          m = YOLO("model.pt")
          m.export(format="onnx", imgsz=imgsz, opset=opset, simplify=True, project="runs", name="export")
          PY

      - name: Find ONNX and compute SHA256
        id: meta
        run: |
          set -euo pipefail
          ONNX=$(find runs/export -name "*.onnx" -type f | head -n1 || true)
          if [ -z "${ONNX}" ]; then
            ONNX=$(find . -name "*.onnx" -type f | head -n1 || true)
          fi
          if [ -z "${ONNX}" ]; then
            echo "::error::Keine .onnx-Datei gefunden. Prüfe Export-Logs oben."
            exit 1
          fi
          echo "[info] Gefundene ONNX: ${ONNX}"
          KEY="${{ github.event.inputs.model_key }}"
          TARGET="${KEY}.onnx"
          cp "$ONNX" "$TARGET"
          SIZE=$(stat -c%s "$TARGET")
          SHA=$(sha256sum "$TARGET" | cut -d ' ' -f1)
          echo "file=$TARGET"   >> $GITHUB_OUTPUT
          echo "size=$SIZE"     >> $GITHUB_OUTPUT
          echo "sha256=$SHA"    >> $GITHUB_OUTPUT

      - name: Create/Update Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: models-${{ github.run_number }}
          name: "YOLO Models build #${{ github.run_number }}"
          draft: false
          prerelease: false
          files: ${{ steps.meta.outputs.file }}

      - name: Install jq (JSON tool)
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Update manifest (yolo-models.json)
        env:
          KEY:   ${{ github.event.inputs.model_key }}
          SIZE:  ${{ steps.meta.outputs.size }}
          SHA:   ${{ steps.meta.outputs.sha256 }}
          REPO:  ${{ github.repository }}
          RUN:   ${{ github.run_number }}
          DISP:  ${{ github.event.inputs.display_name }}
          DESC:  ${{ github.event.inputs.description }}
        run: |
          set -euo pipefail
          MANIFEST="ImageDetection/YOLO/Resources/yolo-models.json"
          URL="https://github.com/${REPO}/releases/download/models-${RUN}/${KEY}.onnx"

          mkdir -p "$(dirname "$MANIFEST")"
          [ -f "$MANIFEST" ] || echo '{}' > "$MANIFEST"

          tmp=$(mktemp)
          jq \
            --arg key "$KEY" \
            --arg url "$URL" \
            --arg sha "$SHA" \
            --argjson size "$SIZE" \
            --arg disp "$DISP" \
            --arg desc "$DESC" \
            '.[$key] = ((.[$key] // {}) + {
                url:        $url,
                sha256:     $sha,
                size:       $size,
                displayName:(if ($disp|length) > 0 then $disp else $key end),
                description:$desc
              })' "$MANIFEST" > "$tmp"
          mv "$tmp" "$MANIFEST"

          echo "[info] Manifest aktualisiert:"
          cat "$MANIFEST"
      
      - name: Create Pull Request for manifest update
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ONNX_Export_Token }}
          commit-message: "chore(manifest): update ${{ github.event.inputs.model_key }}"
          title: "Manifest: ${{ github.event.inputs.model_key }} → models-${{ github.run_number }}"
          body: |
            Auto-PR aus dem Export-Workflow.
            - Modell: `${{ github.event.inputs.model_key }}`
            - Opset:  `${{ github.event.inputs.opset }}`
            - ImgSz:  `${{ github.event.inputs.imgsz }}`
            - Build:  `models-${{ github.run_number }}`
          branch: "ci/manifest-${{ github.event.inputs.model_key }}-${{ github.run_number }}"
          base: ${{ github.event.repository.default_branch }}
          add-paths: |
            ImageDetection/YOLO/Resources/yolo-models.json
          labels: |
            ci
            manifest
          delete-branch: true
