name: Build YOLO ONNX

on:
  workflow_dispatch:
    inputs:
      model_url:
        description: "PT Download-URL (z.B. https://.../yolov8n.pt)"
        required: true
      model_key:
        description: "Kurzname fürs Manifest (z.B. yolov8n)"
        required: true
      imgsz:
        description: "Inputgröße (default 640)"
        default: "640"
      opset:
        description: "ONNX Opset (default 12)"
        default: "12"
      display_name:
        description: "Anzeigename (z.B. YOLOv8 Nano)"
        required: false
        default: ""
      description:
        description: "Kurzbeschreibung fürs UI"
        required: false
        default: ""
      ultralytics_spec:
        description: "pip-Spec für Ultralytics (z.B. ultralytics==8.3.0 oder git+https://...)"
        required: false
        default: "ultralytics>=8.0.0"
      torch_spec:
        description: "OPTIONAL: pip-Spec für torch (z.B. torch==2.3.1)"
        required: false
        default: ""
      extra_pip:
        description: "OPTIONAL: zusätzliche Pakete (mehrere Zeilen möglich)"
        required: false
        default: ""
      pickle_alias_from:
        description: "OPTIONAL: unbekannte Pickle-Klasse (z.B. HumanModel)"
        required: false
        default: ""
      pickle_alias_to:
        description: "OPTIONAL: Zielklasse in ultralytics.nn.tasks (z.B. DetectionModel)"
        required: false
        default: "DetectionModel"

jobs:
  export-onnx:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install deps (CPU-only, version/fork-steuerbar)
        env:
          TORCH_SPEC:       ${{ github.event.inputs.torch_spec }}
          ULTRALYTICS_SPEC: ${{ github.event.inputs.ultralytics_spec }}
          EXTRA_PIP:        ${{ github.event.inputs.extra_pip }}
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip wheel
          if [ -n "${TORCH_SPEC}" ]; then
            echo "[info] Installing torch: ${TORCH_SPEC}"
            pip install "${TORCH_SPEC}"
          fi
          echo "[info] Installing ultralytics: ${ULTRALYTICS_SPEC}"
          pip install "${ULTRALYTICS_SPEC}" onnx onnxsim
          if [ -n "${EXTRA_PIP}" ]; then
            echo "[info] Installing extra packages:"
            printf "%s\n" "${EXTRA_PIP}"
            # Mehrzeiliges Feld Zeile für Zeile an pip übergeben
            while IFS= read -r line; do
              [ -z "$line" ] && continue
              pip install "$line"
            done << 'EOF'
          ${EXTRA_PIP}
EOF
          fi
          echo "[info] Versions:"
          python - << 'PY'
import sys, pkgutil, importlib
def show(name):
    try:
        m = importlib.import_module(name)
        v = getattr(m, '__version__', None)
        print(f"{name}:", v)
    except Exception as e:
        print(f"{name}: <not installed> ({e})")
for n in ["torch","ultralytics","onnx","onnxsim"]:
    show(n)
print("python:", sys.version)
PY

      - name: Download .pt
        run: |
          set -euo pipefail
          curl -fL "${{ github.event.inputs.model_url }}" -o model.pt
          ls -lah

      - name: Export to ONNX (Ultralytics)
        env:
          IMGSZ:             ${{ github.event.inputs.imgsz }}
          OPSET:             ${{ github.event.inputs.opset }}
          PICKLE_ALIAS_FROM: ${{ github.event.inputs.pickle_alias_from }}
          PICKLE_ALIAS_TO:   ${{ github.event.inputs.pickle_alias_to }}
        run: |
          set -euo pipefail
          python - << 'PY'
import os
from ultralytics import YOLO
print("[info] ultralytics import ok")
imgsz = int(os.environ.get("IMGSZ","640"))
opset = int(os.environ.get("OPSET","12"))

# Optionaler Pickle-Alias: z.B. mappe 'HumanModel' -> 'DetectionModel'
alias_from = os.environ.get("PICKLE_ALIAS_FROM","").strip()
alias_to   = os.environ.get("PICKLE_ALIAS_TO","DetectionModel").strip() or "DetectionModel"
if alias_from:
    print(f"[warn] Applying pickle alias: {alias_from} -> {alias_to}")
    import ultralytics.nn.tasks as tasks
    target = getattr(tasks, alias_to, None)
    if target is None:
        raise RuntimeError(f"Zielklasse '{alias_to}' existiert nicht in ultralytics.nn.tasks")
    setattr(tasks, alias_from, target)

print("[info] Lade Modell…")
m = YOLO("model.pt")
print("[info] Export…")
r = m.export(format="onnx", imgsz=imgsz, opset=opset, simplify=True, project="runs", name="export")
print("[info] export result:", r)
PY
          echo "[debug] Inhalt von runs/:"
          find runs -maxdepth 3 -type f -printf "%p (%s bytes)\n" || true

      - name: Find ONNX and compute SHA256
        id: meta
        run: |
          set -euo pipefail
          ONNX=$(find runs/export -name "*.onnx" -type f | head -n1 || true)
          if [ -z "${ONNX}" ]; then
            ONNX=$(find . -name "*.onnx" -type f | head -n1 || true)
          fi
          if [ -z "${ONNX}" ]; then
            echo "::error::Keine .onnx-Datei gefunden. Prüfe Export-Logs oben."
            exit 1
          fi
          echo "[info] Gefundene ONNX: ${ONNX}"
          KEY="${{ github.event.inputs.model_key }}"
          TARGET="${KEY}.onnx"
          cp "$ONNX" "$TARGET"
          SIZE=$(stat -c%s "$TARGET")
          SHA=$(sha256sum "$TARGET" | cut -d ' ' -f1)
          echo "file=$TARGET"   >> $GITHUB_OUTPUT
          echo "size=$SIZE"     >> $GITHUB_OUTPUT
          echo "sha256=$SHA"    >> $GITHUB_OUTPUT

      - name: Create/Update Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: models-${{ github.run_number }}
          name: "YOLO Models build #${{ github.run_number }}"
          draft: false
          prerelease: false
          files: ${{ steps.meta.outputs.file }}

      - name: Install jq (JSON tool)
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Update manifest (yolo-models.json)
        env:
          KEY:   ${{ github.event.inputs.model_key }}
          SIZE:  ${{ steps.meta.outputs.size }}
          SHA:   ${{ steps.meta.outputs.sha256 }}
          REPO:  ${{ github.repository }}
          RUN:   ${{ github.run_number }}
          DISP:  ${{ github.event.inputs.display_name }}
          DESC:  ${{ github.event.inputs.description }}
        run: |
          set -euo pipefail
          MANIFEST="ImageDetection/YOLO/Resources/yolo-models.json"
          URL="https://github.com/${REPO}/releases/download/models-${RUN}/${KEY}.onnx"

          mkdir -p "$(dirname "$MANIFEST")"
          [ -f "$MANIFEST" ] || echo '{}' > "$MANIFEST"

          tmp=$(mktemp)
          jq \
            --arg key "$KEY" \
            --arg url "$URL" \
            --arg sha "$SHA" \
            --argjson size "$SIZE" \
            --arg disp "$DISP" \
            --arg desc "$DESC" \
            '.[$key] = ((.[$key] // {}) + {
                url:        $url,
                sha256:     $sha,
                size:       $size,
                displayName:(if ($disp|length) > 0 then $disp else $key end),
                description:$desc
              })' "$MANIFEST" > "$tmp"
          mv "$tmp" "$MANIFEST"

          echo "[info] Manifest aktualisiert:"
          cat "$MANIFEST"
      
      - name: Create Pull Request for manifest update
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ONNX_Export_Token }}
          commit-message: "chore(manifest): update ${{ github.event.inputs.model_key }}"
          title: "Manifest: ${{ github.event.inputs.model_key }} → models-${{ github.run_number }}"
          body: |
            Auto-PR aus dem Export-Workflow.
            - Modell: `${{ github.event.inputs.model_key }}`
            - Opset:  `${{ github.event.inputs.opset }}`
            - ImgSz:  `${{ github.event.inputs.imgsz }}`
            - Build:  `models-${{ github.run_number }}`
          branch: "ci/manifest-${{ github.event.inputs.model_key }}-${{ github.run_number }}"
          base: ${{ github.event.repository.default_branch }}
          add-paths: |
            ImageDetection/YOLO/Resources/yolo-models.json
          labels: |
            ci
            manifest
          delete-branch: true
